Resources:
https://www.learnpytorch.io/
https://github.com/mrdbourke/pytorch-deep-learning

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
print(torch.__version__)

2.3.0+cu121


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
##Introduction to Tensors

###Creating a tensor
scalar = torch.tensor(7)

In [ ]:
vector = torch.tensor([7,7])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#dim is no of sq brack, shape is items

In [ ]:
MATRIX = torch.tensor([[7,8],[8,9]])

In [ ]:
MATRIX.ndim


2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR  = torch.tensor([[[1,2,3],[3,4,5],[5,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape


torch.Size([1, 3, 3])

In [ ]:
#this means it has a 1 3X3 matrix

In [ ]:
T1 = torch.tensor([[[[1,2],[2,3],[3,4]],[[1,2],[2,3],[3,4]]]])
print(T1.ndim)
print(T1.shape)
print(T1[0])

4
torch.Size([1, 2, 3, 2])
tensor([[[1, 2],
         [2, 3],
         [3, 4]],

        [[1, 2],
         [2, 3],
         [3, 4]]])


In [ ]:
tensor_A = torch.tensor([1,2,3])

In [ ]:
tensor_A *10

tensor([10, 20, 30])

In [ ]:
tensor_A @ tensor_A

tensor(14)

In [ ]:
torch.matmul(tensor_A,tensor_A)

RuntimeError: tensor.mT is only supported on matrices or batches of matrices. Got 1-D tensor.

In [ ]:
tensor_B = torch.tensor([[1],[2],[3]])

In [ ]:
print(f"tensor A shape: {tensor_A.shape}")
print(f"tensor B shape: {tensor_B.shape}")
print("matric Multiplication gives: {tensor_A.shape} @ {tensor_B.shape}")
output = torch.matmul(tensor_A,tensor_B)
print(output)
print(f"Output shape: {output.shape}")

tensor A shape: torch.Size([3])
tensor B shape: torch.Size([3, 1])
matric Multiplication gives: {tensor_A.shape} @ {tensor_B.shape}
tensor([14])
Output shape: torch.Size([1])


##Indexing tensors


In [5]:
import torch
tens = torch.arange(1,10).reshape(3,3)
tens2 = torch.arange(1,10).reshape(1,3,3)
#print(tens, tens2)
tens[:,0]
tens[:,1]

tensor([2, 5, 8])

#Numpy and Torch tensors
Numpy is a popular scientific python numerical computing library

* data in numpy and to convert it ot tensors use -> `torch.from_numpy(ndarray)`
* PyTorch tensor if you want to convert it into a numpy array then use -> `torch,Tensor.numpy()`

----
Note
When converting from arrayt to tensors it is by default float 64. so keep in muind thast it si nnot tensor default data tyope

In [9]:
import torch
import numpy as np
#numpy array to tensor
array = np.arange(1,8)
tensor = torch.from_numpy(array).type(torch.float32)
array,tensor


#tensor. to array
tensor1 = torch.ones(7)
numpy_tensor = tensor1.numpy()
tensor1, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility: (Trying to take the random out of random)

In short how a neural network learns i s
`astart wuith random numbers -. tensor operations -> update the random numbers to try and talke them to make better of the data ->l again -> again ->again `

To reduce the randomness in newural networks and pytorch comes the convept of a **random seed**

Essentially what the random seed does is "flavour" the randomness and gives a starting point gfor generating the randomness

**psuedo-randomness**
* https://pytorch.org/docs/stable/notes/randomness.html

In [13]:
random_tensor_A = torch.rand(3,3)
random_tensor_B = torch.rand(3,3)
print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_B == random_tensor_A)
#here you notive theya re never equeal and true random


tensor([[0.0930, 0.9120, 0.1372],
        [0.0021, 0.9677, 0.7968],
        [0.3165, 0.1682, 0.6442]])
tensor([[0.5313, 0.1322, 0.9038],
        [0.6314, 0.1525, 0.7211],
        [0.0435, 0.9670, 0.4240]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [14]:
import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,3)
#note: you need to provide the seed again before any random generation else it does not get applied to the random generator
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,3)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


## Running tensors and pyutorch objects obn GPUs and making faster computations.

GPUs = faster copmputations on numbers, CUDA+NVIDIAhardware

### Gettign a GPU:
* colab pro
* set up your own - https://www.run.ai/guides/gpu-deep-learning/best-gpu-for-deep-learning
* use cloud computing in GCP/AWS etc

`import torch
 torch.cuda.is_available()`

 Devide Agnostic:
 `device = "cuda' if torch.cuda_is_avaialbel() else "cpu"`

 `torch.cuda.device_count()`